package com.projectfaust.institution;

import com.projectfaust.institution.dto.InstitutionIdentifierRequest;
import com.projectfaust.institution.dto.InstitutionIdentifierResponse;
import org.mapstruct.*;

import java.util.List;

/**
 * MapStruct mapper for {@link InstitutionIdentifier} within Project Faust.
 *
 * <p>Handles two mapping concerns:</p>
 * <ul>
 *   <li><b>Entity → response</b> — maps a persisted identifier to the
 *       {@link InstitutionIdentifierResponse} DTO surfaced via the API.</li>
 *   <li><b>Request → entity</b> — initialises a new {@link InstitutionIdentifier}
 *       from a validated request, excluding fields managed by JPA or the
 *       service layer ({@code id}, {@code institution}, {@code active},
 *       {@code createdAt}, {@code updatedAt}).</li>
 * </ul>
 *
 * <p>Country code normalisation (trim + uppercase) is applied in the
 * service layer before the mapper is called — the mapper assumes the value
 * is already clean.</p>
 *
 * @author Dimitri / Project Faust
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface InstitutionIdentifierMapper {

    // -------------------------------------------------------------------------
    // Entity → response
    // -------------------------------------------------------------------------

    /**
     * Maps a persisted {@link InstitutionIdentifier} to a response DTO.
     *
     * @param entity the identifier entity.
     * @return the response DTO.
     */
    InstitutionIdentifierResponse toResponse(InstitutionIdentifier entity);

    /**
     * Maps a list of identifiers to response DTOs.
     *
     * @param entities list of identifier entities.
     * @return list of response DTOs.
     */
    List<InstitutionIdentifierResponse> toResponseList(List<InstitutionIdentifier> entities);

    // -------------------------------------------------------------------------
    // Request → entity
    // -------------------------------------------------------------------------

    /**
     * Initialises a new {@link InstitutionIdentifier} entity from a
     * validated request DTO.
     *
     * <p>The following fields are excluded and managed elsewhere:</p>
     * <ul>
     *   <li>{@code id} — generated by JPA.</li>
     *   <li>{@code institution} — set by the service via
     *       {@link Institution#addIdentifier(InstitutionIdentifier)}.</li>
     *   <li>{@code active} — defaults to {@code true} on the entity builder.</li>
     *   <li>{@code createdAt} / {@code updatedAt} — set by {@code @PrePersist}.</li>
     * </ul>
     *
     * @param request the validated creation request.
     * @return an entity ready for institution assignment and persistence.
     */
    @Mapping(target = "id",          ignore = true)
    @Mapping(target = "institution", ignore = true)
    @Mapping(target = "active",      ignore = true)
    @Mapping(target = "createdAt",   ignore = true)
    @Mapping(target = "updatedAt",   ignore = true)
    InstitutionIdentifier toEntity(InstitutionIdentifierRequest request);
}
