package com.projectfaust.intelligence;

import com.projectfaust.person.Person;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.envers.Audited;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Entity representing an AI-generated intelligence analysis report for a person.
 *
 * <p>Reports are generated by the AI analyst layer and stored for historical
 * tracking — each report captures the analysis result, model version, and
 * a risk score at the time of generation.</p>
 *
 * @author Dimitri / Project Faust
 */
@Entity
@Table(name = "intelligence_reports", indexes = {
        @Index(name = "idx_intel_report_ext_id",   columnList = "externalId"),
        @Index(name = "idx_intel_report_person_id", columnList = "person_id"),
        @Index(name = "idx_intel_report_generated", columnList = "generatedAt")
})
@Audited
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IntelligenceReport {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Public-facing UUID for API exposure.
     */
    @Builder.Default
    @Column(nullable = false, unique = true, updatable = false)
    @JdbcTypeCode(SqlTypes.UUID)
    private UUID externalId = UUID.randomUUID();

    /**
     * The subject person this report analyses.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "person_id")
    private Person person;

    /**
     * Full AI-generated analysis text. Stored as TEXT for variable-length outputs.
     */
    @Column(columnDefinition = "TEXT")
    private String analysisResult;

    /**
     * Risk score assigned by the AI model at generation time (0–10).
     * Stored on the entity — never hardcoded in the mapper.
     */
    private Integer riskScore;

    /**
     * Timestamp when this report was generated. Timezone-aware.
     */
    private OffsetDateTime generatedAt;

    /**
     * Version identifier of the AI model that produced this report.
     * Enables model drift detection and result reproducibility auditing.
     */
    private String modelVersion;
}