package com.projectfaust.location;

import com.projectfaust.location.dto.LocationRequest;
import com.projectfaust.location.dto.LocationResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for the {@link Location} domain.
 *
 * <p>Handles bidirectional transformation between the geographic persistence entity
 * and its DTO projections, maintaining two key principles:</p>
 *
 * <ul>
 *   <li><b>Flat API surface</b> — the nested {@code parent} relationship is never
 *       serialised as a full object. Instead, only {@code parentExternalId} and
 *       {@code parentName} are exposed, preventing unbounded graph serialisation
 *       and avoiding internal ID leakage.</li>
 *   <li><b>Service-managed fields</b> — technical identifiers ({@code id},
 *       {@code externalId}), audit timestamps, relational collections, and
 *       intelligence metadata ({@code verificationStatus}, {@code sourceType})
 *       are excluded from {@code toEntity} mapping and handled exclusively by
 *       the service and persistence layer.</li>
 * </ul>
 *
 * @author Dimitri / Project Faust
 */
@Mapper(componentModel = "spring")
public interface LocationMapper {

    /**
     * Maps a {@link Location} persistence entity to a {@link LocationResponse} DTO.
     *
     * <p>The parent relationship is flattened into two scalar fields for client
     * consumption. The {@code hasChildren} flag is derived from the size of the
     * children collection — note this expression requires an active Hibernate
     * session (i.e., must be called within a {@code @Transactional} boundary)
     * to avoid a {@code LazyInitializationException}.</p>
     *
     * @param location the geographic persistence entity.
     * @return a flattened {@link LocationResponse} safe for REST serialisation.
     */
    @Mapping(target = "parentExternalId", source = "parent.externalId")
    @Mapping(target = "parentName",       source = "parent.name")
    @Mapping(target = "hasChildren",
            expression = "java(location.getChildren() != null && !location.getChildren().isEmpty())")
    LocationResponse toResponse(Location location);

    /**
     * Initialises a new {@link Location} entity from a {@link LocationRequest} DTO.
     *
     * <p>The following fields are intentionally ignored and must be set by the
     * calling service or by JPA lifecycle callbacks:</p>
     * <ul>
     *   <li>{@code id} — assigned by the persistence provider.</li>
     *   <li>{@code externalId} — generated by {@code @Builder.Default} on the entity.</li>
     *   <li>{@code parent} — resolved from {@code parentExternalId} by the service.</li>
     *   <li>{@code children} — managed by JPA; initialised as empty list on the entity.</li>
     *   <li>{@code createdAt} / {@code updatedAt} — set by {@code @PrePersist} / {@code @PreUpdate}.</li>
     *   <li>{@code verificationStatus} — defaults to {@code PENDING_REVIEW} for all new nodes;
     *       promoted by an analyst after verification.</li>
     *   <li>{@code sourceType} — set by the service based on the ingestion channel.</li>
     * </ul>
     *
     * @param request the DTO containing operator-supplied location attributes.
     * @return a {@link Location} entity ready for parent assignment and persistence.
     */
    @Mapping(target = "id",                 ignore = true)
    @Mapping(target = "externalId",         ignore = true)
    @Mapping(target = "parent",             ignore = true)
    @Mapping(target = "children",           ignore = true)
    @Mapping(target = "createdAt",          ignore = true)
    @Mapping(target = "updatedAt",          ignore = true)
    @Mapping(target = "verificationStatus", ignore = true)
    @Mapping(target = "sourceType",         ignore = true)
    Location toEntity(LocationRequest request);
}