package com.projectfaust.traces.dto.response;

import com.projectfaust.traces.enums.TraceConfidence;
import com.projectfaust.traces.enums.TraceSourceType;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Chronological aggregation of all trace types for a single subject.
 *
 * <p>Used by the analyst dossier view to display a unified activity timeline
 * across digital, financial, camera, telco and surveillance data sources.</p>
 */
public record TraceTimelineResponse(

        UUID personPublicId,
        String personFullName,

        LocalDateTime from,
        LocalDateTime to,

        int totalEvents,
        Map<String, Integer> countByType,   // "DIGITAL" → 12, "FINANCIAL" → 3, …
        Map<String, Integer> countByCountry,// "CZ" → 8, "DE" → 5, …

        /** All events in ascending chronological order. */
        List<TimelineEntry> entries
) {

    /**
     * A single event on the timeline — type-tagged union wrapping the
     * type-specific payload as an opaque record.
     *
     * <p>The {@link #traceType} discriminator tells the client which DTO
     * is in {@link #payload} so it can deserialise / render correctly.</p>
     */
    public record TimelineEntry(
            UUID traceExternalId,
            String traceType,           // "DIGITAL" | "FINANCIAL" | "CAMERA" | "TELCO" | "SURVEILLANCE"
            LocalDateTime observedAt,
            TraceSourceType sourceType,
            TraceConfidence confidence,
            boolean flagged,

            /**
             * Short human-readable summary generated by the service layer for
             * quick timeline display without needing to inspect the full payload.
             * E.g. "Card payment — Tesco CZ · Prague · 1 200 CZK"
             */
            String summary,

            /**
             * Optional geo-coordinates — present when the trace carries a
             * meaningful physical location (camera, telco cell, financial terminal,
             * surveillance event).  Null for pure digital traces.
             */
            Double latitude,
            Double longitude,
            String country,
            String city,

            /** The full typed payload — one of the five *Response records. */
            Object payload
    ) {}
}
